version: 2.1

commands:
  setup_environment:
    description: "Setup testing environment"
    parameters:
      cache_key:
        type: string
        default: aleo-stable-cache
    steps:
      - run: set -e
      - setup_remote_docker
      - run:
          name: Prepare environment and install dependencies
          command: |
            export SCCACHE_CACHE_SIZE=200M
            export WORK_DIR="$CIRCLE_WORKING_DIRECTORY/.cache/sccache"
            export SCCACHE_DIR="$CIRCLE_WORKING_DIRECTORY/.cache/sccache"
            mkdir -p "$CIRCLE_WORKING_DIRECTORY/.bin"
            wget https://github.com/mozilla/sccache/releases/download/0.2.13/sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
            tar -C "$CIRCLE_WORKING_DIRECTORY/.bin" -xvf sccache-0.2.13-x86_64-unknown-linux-musl.tar.gz
            mv $CIRCLE_WORKING_DIRECTORY/.bin/sccache-0.2.13-x86_64-unknown-linux-musl/sccache $CIRCLE_WORKING_DIRECTORY/.bin/sccache
            export PATH="$PATH:$CIRCLE_WORKING_DIRECTORY/.bin"
            export RUSTC_WRAPPER="sccache"
            rm -rf "$CIRCLE_WORKING_DIRECTORY/.cargo/registry"
            sudo apt-get update && sudo apt-get install -y clang llvm-dev llvm pkg-config xz-utils make libssl-dev libssl-dev
      - restore_cache:
          keys:
            - << parameters.cache_key >>

  clear_environment:
    description: "Clear environment"
    parameters:
      cache_key:
        type: string
        default: aleo-stable-cache
    steps:
      - run: (sccache -s||true)
      - run: set +e
      - save_cache:
          key: << parameters.cache_key >>
          paths:
            - .cache/sccache
            - .cargo

  run_serial:
    description: "Build and run tests"
    parameters:
      workspace_member:
        type: string
      cache_key:
        type: string
      flags:
        type: string
        default: ""
    steps:
      - checkout
      - setup_environment:
          cache_key: << parameters.cache_key >>
      - run:
          no_output_timeout: 30m
          command: cd << parameters.workspace_member >> && RUST_MIN_STACK=67108864 cargo test << parameters.flags >>
      - clear_environment:
          cache_key: << parameters.cache_key >>

  run_parallel:
    description: "Build and run tests (in parallel)"
    parameters:
      workspace_member:
        type: string
      cache_key:
        type: string
      flags:
        type: string
        default: ""
    steps:
      - checkout
      - setup_environment:
          cache_key: << parameters.cache_key >>
      - run:
          no_output_timeout: 30m
          command: |
            cd << parameters.workspace_member >>
            cargo test -- --list --format terse | sed 's/: test//' > test_names.txt
            TEST_NAMES=$(circleci tests split test_names.txt)
            for i in $(echo $TEST_NAMES | sed "s/ / /g")
            do
                RUST_MIN_STACK=67108864 cargo test $i << parameters.flags >>
            done
      - clear_environment:
          cache_key: << parameters.cache_key >>

jobs:
  rust_stable:
    docker:
      - image: cimg/rust:1.70
    resource_class: xlarge
    steps:
      - run_serial:
          workspace_member: .
          cache_key: aleo-stable-cache

  check-fmt:
    docker:
      - image: cimg/rust:1.70
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: aleo-fmt-cache
      - run:
          name: Check style
          no_output_timeout: 35m
          command: |
            rustup toolchain install nightly-x86_64-unknown-linux-gnu
            cargo +nightly fmt --all -- --check
      - clear_environment:
          cache_key: aleo-fmt-cache

  check-clippy:
    docker:
      - image: cimg/rust:1.70
    resource_class: 2xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: aleo-clippy-cache
      - run:
          name: Check lint
          no_output_timeout: 35m
          command: |
            cargo clippy --workspace --all-targets --all-features
      - clear_environment:
          cache_key: aleo-clippy-cache

  aleo-deploy-and-execute:
    docker:
      - image: cimg/rust:1.70
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: aleo-executable-cache
      - run:
          name: Install snarkos and test deploy & execute
          no_output_timeout: 30m
          command: |
            cargo install snarkos
            snarkos start --dev 0 --validator --nodisplay 1> /dev/null &
            snarkos start --dev 1 --validator --nodisplay 1> /dev/null &
            snarkos start --dev 2 --validator --nodisplay 1> /dev/null &
            snarkos start --dev 3 --validator --nodisplay 1> /dev/null &
            sleep 480
            cd rust
            cargo test test_mappings_query -- --ignored --nocapture --test-threads=1
            cargo test test_transfer_roundtrip -- --ignored --nocapture --test-threads=1
            cargo test test_deploy -- --ignored --nocapture --test-threads=1
            cargo test test_execution -- --ignored --nocapture --test-threads=1

  aleo-executable:
    docker:
      - image: cimg/rust:1.70
    resource_class: xlarge
    steps:
      - checkout
      - setup_environment:
          cache_key: aleo-executable-cache
      - run:
          name: Build and install Aleo CLI
          no_output_timeout: 30m
          command: |
            cargo install --path . --root . --locked
            export ALEO=/home/circleci/project/bin/aleo
            ./.circleci/aleo-new.sh

      - persist_to_workspace:
          root: ~/
          paths:
            - project/
      - clear_environment:
          cache_key: aleo-executable-cache

workflows:
  version: 2

  main-workflow:
    jobs:
      - rust_stable
      - check-fmt
      - check-clippy
      - aleo-executable
      - aleo-deploy-and-execute
